export const cartList = [
    {
        id: 1,
        theme: "Web Design",
        color: "_orange",
        title: "Название задачи",
        date: "30.10.2023",
        status: "Без статуса",
    },
    {
        id: 2,
        theme: "Research",
        color: "_green",
        title: "Название задачи",
        date: "30.10.2023",
        status: "Без статуса",
    },
    {
        id: 3,
        theme: "Web Design",
        color: "_orange",
        title: "Название задачи",
        date: "30.10.2023",
        status: "Без статуса",
    },
    {
        id: 4,
        theme: "Copywriting",
        color: "_purple",
        title: "Название задачи",
        date: "30.10.2023",
        status: "Без статуса",
    },
    {
        id: 5,
        theme: "Web Design",
        color: "_orange",
        title: "Название задачи",
        date: "30.10.2023",
        status: "Без статуса",
    },
    {
        id: 6,
        theme: "Research",
        color: "_green",
        title: "Название задачи",
        date: "30.10.2023",
        status: "Нужно сделать",
    },
    {
        id: 7,
        theme: "Research",
        color: "_green",
        title: "Название задачи",
        date: "30.10.2023",
        status: "В работе",
    },
    {
        id: 8,
        theme: "Copywriting",
        color: "_purple",
        title: "Название задачи",
        date: "30.10.2023",
        status: "В работе",
    },
    {
        id: 9,
        theme: "Web Design",
        color: "_orange",
        title: "Название задачи",
        date: "30.10.2023",
        status: "В работе",
    },
    {
        id: 10,
        theme: "Research",
        color: "_green",
        title: "Название задачи",
        date: "30.10.2023",
        status: "Тестирование",
    },
    {
        id: 11,
        theme: "Research",
        color: "_green",
        title: "Название задачи",
        date: "30.10.2023",
        status: "Готово",
    },
]
